"""add desc to links

Revision ID: 0ff9eb7af9c3
Revises: 9f03afdc82bc
Create Date: 2026-02-23 15:57:33.365986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff9eb7af9c3'
down_revision: Union[str, Sequence[str], None] = '9f03afdc82bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'description')
    # ### end Alembic commands ###
