"""add click_count to links

Revision ID: ccc2cc143c25
Revises: c81cce1da5da
Create Date: 2026-02-23 16:11:46.173080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc2cc143c25'
down_revision: Union[str, Sequence[str], None] = 'c81cce1da5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable
    op.add_column('links', sa.Column('click_count', sa.Integer(), nullable=True))

    # Step 2: Backfill existing rows
    op.execute("UPDATE links SET click_count = 0")

    # Step 3: Make column NOT NULL
    op.alter_column('links', 'click_count', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'click_count')
    # ### end Alembic commands ###
